name: school_num_flutter
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  event_bus:  ^1.0.1
  dio: ^1.0.4
  flutter_webview_plugin: ^0.2.1+2

  shared_preferences: ^0.4.2
  image_picker: ^0.4.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.schoolnumflutter

  assets:
     - images/

